CREATE DATABASE IF NOT EXISTS MyDb COMMENT 'Create Database';
use MyDb;
CREATE EXTERNAL TABLE IF NOT EXISTS MyDb.foodplaces (
id INT COMMENT 'Resturant id',
place STRING COMMENT 'Where the resturant is'
)
COMMENT 'Food Places'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;